package error

import (
	"entain/internal/domain"
)

var (
	// ErrBadRouting is returned when an expected path variable is missing.
	// It always indicates programmer error.
	ErrBadRouting = NewErrInternal("inconsistent mapping between route and handler")
)

// DefaultErrResponse is the default error that is generated by the gateway.
// swagger:model defaultErrorResponse
type DefaultErrResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// ErrResponse is the default error response that is generated by the gateway.
// swagger:response errorResponse
type ErrResponse struct {
	// in: body
	Body struct {
		Status domain.ResponseStatus `json:"status"`
		Data   interface{}           `json:"data"`
		Error  *DefaultErrResponse   `json:"error"`
	} `json:"body"`
}

var (
	_ domain.Bodier = ErrResponse{}
)

// GetBody implements helpers.Bodier.
func (r ErrResponse) GetBody() interface{} { return r.Body }
